### ISSUE TITLE
Build failure under Visual C++ 

### ISSUE THREAD

**Issue by mindw** [VariationalRegistration/VariationalRegistration#1]
There is no "getopt.h" header in Win32.

**Comment by aschmiri** [comment]
Hi,
thanks for reporting, we're looking into it!
Best
Alex

**Comment by renewerner** [comment]
Build errors should be fixed now. We did not test the registration methods themselves under VS, though. Will do so in near future.
Best, 
Rene

**Comment by aschmiri** [comment]
Hi,

just as an addition: To include the current build you have to change the linked Git tag to the current branch, because it is not yet patched in ITK. To do this, just change in the file

<ITK_DIR>/Modules/Remote/VariationalRegistration.remote.cmake

line 8 to

```
GIT_TAG 10cfd09b64428576f90b19ce12332212aa2b87d5
```

Please let us know if you encounter any problems!

Cheers
Alex
